
stages:
- build dev docker image
- build latest docker image
- build tagged docker image

jobs:
    
    include:

        # Publish dev image on docker hub
        - stage: build dev docker image
          if: 
            - branch != "main" AND branchAND NOT tag IS present
          script:
          - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
          - export IMAGE_TAG = dev
          - make push

        # Publish latest image on docker hub [MAIN ONLY]
        - stage: build latest docker image
          if: 
            - NOT tag IS present AND branch = "main"
          script:
          - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
          - export IMAGE_TAG=latest
          - make push
    
        # Publish tagged image on docker hub 
        - stage: build tagged docker image
          if: 
            - tag IS present
          script:
          - export IMAGE_TAG=${TRAVIS_TAG}
          - make push
