version: 2
jobs:
  build_and_push_dev:
    environment:
      IMAGE_TAG: dev
    docker:
      - image: circleci/buildpack-deps:stretch
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: login docker hub
          command: |
            echo "$DOCKERHUB_PASS" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
      - run:
          name: Build Docker image
          command: make push

  build_and_push_latest:
      environment:
        IMAGE_TAG: latest
      docker:
        - image: circleci/buildpack-deps:stretch
      steps:
        - checkout
        - setup_remote_docker
        - run:
            name: login docker hub
            command: |
              echo "$DOCKERHUB_PASS" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
        - run:
            name: Build Docker image
            command: make push
      
  build_and_push_tagged:
    environment:
      IMAGE_TAG: $CIRCLE_TAG
    docker:
      - image: circleci/buildpack-deps:stretch
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: login docker hub
          command: |
            echo "$DOCKERHUB_PASS" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
      - run:
          name: Build Docker image
          command: make push

workflows:
  version: 2
  build-dev:
    jobs:
      - build_and_push_dev:
          filters:
            branches:
              ignore:
                - main
                - master
      
      - build_and_push_latest:
          filters:
            branches:
              only:
                - main
                - master
      
      - build_and_push_tagged:
          filters:
            tags:
              only:
                - /.+/
